export default {
  Circle: 'circle',
  Line: 'line',
  Arrow: 'arrow',
  Pencil: 'pencil',
  Rectangle: 'rectangle',
  RectangleLabel: 'rectangle-label',
  Select: 'select',
  Pan: 'pan',
  Triangle: 'triangle',
  Remove: 'remove',
  Text: 'text',
  Ellipse: 'ellipse',
  DefaultTool: 'default-tool',
  Polygon: 'polygon',
  Pointer: 'pointer',
}